server:
  port: 8080

logging:
  level:
    com:
      hedvig: DEBUG

spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  profiles:
    active: development
