'use strict';

/* eslint-env browser */
/* global module */

import 'babel-polyfill';
import React from 'react';
import ReactDOM from 'react-dom';
import './app.css';

const appElement = document.getElementById('react');

ReactDOM.render(
    <div className="pink">
        <h1>Hello from ReactJs</h1>
        <p>What we have now</p>
        <ul>
            <li>Simple ReactJs application</li>
            <li>JS and CSS generated by Webpack for both production and development</li>
            <li>Spring boot for the REST API</li>
        </ul>
    </div>,
    appElement
);

if (module.hot) {
    module.hot.accept();
}
