// TODO add all action types
export default {
    LOGIN_USER: 'LOGIN_USER',
    SENDING_REQUEST: 'SENDING_REQUEST',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    SET_AUTH: 'SET_AUTH',
    LOGOUT: 'LOGOUT',
    CHANGE_FORM: 'CHANGE_FORM',
    REQUEST_ERROR: 'REQUEST_ERROR',
    FETCH_ASSETS_REQUEST: 'FETCH_ASSETS_REQUEST',
    FETCH_ASSETS_SUCCESS: 'FETCH_ASSETS_SUCCESS',
    FETCH_ASSETS_ERROR: 'FETCH_ASSETS_ERROR',
    UPDATE_ASSET_REQUEST: 'UPDATE_ASSET_REQUEST',
    UPDATE_ASSET_SUCCESS: 'UPDATE_ASSET_SUCCESS',
    UPDATE_ASSET_ERROR: 'UPDATE_ASSET_ERROR'
}